### ISSUE TITLE
Use http4s instead of github4s

### ISSUE THREAD

**Issue by Kevin-Lee** [Kevin-Lee/sbt-devoops#146]
# Task

## Summary 
Use http4s instead of github4s

## Project Details
Version: `1.0.3`

## Description
**Since github4s doesn't support uploading assets to release**, it is required to use HTTP client library to do both release and loading. So use http4s instead of github4s which means #140 can be dropped.

- [x] New data types for GitHub release
- [x] Add create GitHub release
- [x] Add find GitHub release
- [x] Add update GitHub release
- [x] Add upload assets to GitHub release
- [ ] Replace the `OldGitHubApi` with the new `GitHubApi`.

**Comment by Kevin-Lee** [comment]
This is blocked by http4s/http4s#4303. 😭
